    m.def("from_numpy", from_numpy<int32_t>);
    m.def("from_numpy", from_numpy<int64_t>);
    m.def("from_numpy", from_numpy<uint32_t>);
    m.def("from_numpy", from_numpy<uint64_t>);
    m.def("from_numpy", from_numpy<_Float64>);
    m.def("from_pylist", from_pylist<int32_t>);
    m.def("from_pylist", from_pylist<int64_t>);
    m.def("from_pylist", from_pylist<uint32_t>);
    m.def("from_pylist", from_pylist<uint64_t>);
    m.def("from_pylist", from_pylist<_Float64>);
    m.def("to_numpy", to_numpy<int32_t>);
    m.def("to_numpy", to_numpy<int64_t>);
    m.def("to_numpy", to_numpy<uint32_t>);
    m.def("to_numpy", to_numpy<uint64_t>);
    m.def("to_numpy", to_numpy<_Float64>);
    m.def("to_list", to_list<int32_t>);
    m.def("to_list", to_list<int64_t>);
    m.def("to_list", to_list<uint32_t>);
    m.def("to_list", to_list<uint64_t>);
    m.def("to_list", to_list<_Float64>);
    m.def("fill", Fill<int32_t>);
    m.def("fill", Fill<int64_t>);
    m.def("fill", Fill<uint32_t>);
    m.def("fill", Fill<uint64_t>);
    m.def("fill", Fill<_Float64>);
    m.def("compact", Compact<int32_t>);
    m.def("compact", Compact<int64_t>);
    m.def("compact", Compact<uint32_t>);
    m.def("compact", Compact<uint64_t>);
    m.def("compact", Compact<_Float64>);
    m.def("ewise_setitem", EwiseSetitem<int32_t>);
    m.def("ewise_setitem", EwiseSetitem<int64_t>);
    m.def("ewise_setitem", EwiseSetitem<uint32_t>);
    m.def("ewise_setitem", EwiseSetitem<uint64_t>);
    m.def("ewise_setitem", EwiseSetitem<_Float64>);
    m.def("scalar_setitem", ScalarSetitem<int32_t>);
    m.def("scalar_setitem", ScalarSetitem<int64_t>);
    m.def("scalar_setitem", ScalarSetitem<uint32_t>);
    m.def("scalar_setitem", ScalarSetitem<uint64_t>);
    m.def("scalar_setitem", ScalarSetitem<_Float64>);
    m.def("scalar_power", ScalarPower<int32_t>);
    m.def("scalar_power", ScalarPower<int64_t>);
    m.def("scalar_power", ScalarPower<uint32_t>);
    m.def("scalar_power", ScalarPower<uint64_t>);
    m.def("scalar_power", ScalarPower<_Float64>);
    m.def("ewise_eq", EwiseEq<int32_t>);
    m.def("ewise_eq", EwiseEq<int64_t>);
    m.def("ewise_eq", EwiseEq<uint32_t>);
    m.def("ewise_eq", EwiseEq<uint64_t>);
    m.def("ewise_eq", EwiseEq<_Float64>);
    m.def("scalar_eq", ScalarEq<int32_t>);
    m.def("scalar_eq", ScalarEq<int64_t>);
    m.def("scalar_eq", ScalarEq<uint32_t>);
    m.def("scalar_eq", ScalarEq<uint64_t>);
    m.def("scalar_eq", ScalarEq<_Float64>);
    m.def("ewise_log", EwiseLog<int32_t>);
    m.def("ewise_log", EwiseLog<int64_t>);
    m.def("ewise_log", EwiseLog<uint32_t>);
    m.def("ewise_log", EwiseLog<uint64_t>);
    m.def("ewise_log", EwiseLog<_Float64>);
    m.def("ewise_exp", EwiseExp<int32_t>);
    m.def("ewise_exp", EwiseExp<int64_t>);
    m.def("ewise_exp", EwiseExp<uint32_t>);
    m.def("ewise_exp", EwiseExp<uint64_t>);
    m.def("ewise_exp", EwiseExp<_Float64>);
    m.def("ewise_tanh", EwiseTanh<int32_t>);
    m.def("ewise_tanh", EwiseTanh<int64_t>);
    m.def("ewise_tanh", EwiseTanh<uint32_t>);
    m.def("ewise_tanh", EwiseTanh<uint64_t>);
    m.def("ewise_tanh", EwiseTanh<_Float64>);
    m.def("reduce_max", ReduceMax<int32_t>);
    m.def("reduce_max", ReduceMax<int64_t>);
    m.def("reduce_max", ReduceMax<uint32_t>);
    m.def("reduce_max", ReduceMax<uint64_t>);
    m.def("reduce_max", ReduceMax<_Float64>);
    m.def("reduce_sum", ReduceSum<int32_t>);
    m.def("reduce_sum", ReduceSum<int64_t>);
    m.def("reduce_sum", ReduceSum<uint32_t>);
    m.def("reduce_sum", ReduceSum<uint64_t>);
    m.def("reduce_sum", ReduceSum<_Float64>);
    m.def("from_handle", from_handle<int32_t, int32_t>);
    m.def("from_handle", from_handle<int32_t, int64_t>);
    m.def("from_handle", from_handle<int32_t, uint32_t>);
    m.def("from_handle", from_handle<int32_t, uint64_t>);
    m.def("from_handle", from_handle<int32_t, _Float64>);
    m.def("from_handle", from_handle<int64_t, int32_t>);
    m.def("from_handle", from_handle<int64_t, int64_t>);
    m.def("from_handle", from_handle<int64_t, uint32_t>);
    m.def("from_handle", from_handle<int64_t, uint64_t>);
    m.def("from_handle", from_handle<int64_t, _Float64>);
    m.def("from_handle", from_handle<uint32_t, int32_t>);
    m.def("from_handle", from_handle<uint32_t, int64_t>);
    m.def("from_handle", from_handle<uint32_t, uint32_t>);
    m.def("from_handle", from_handle<uint32_t, uint64_t>);
    m.def("from_handle", from_handle<uint32_t, _Float64>);
    m.def("from_handle", from_handle<uint64_t, int32_t>);
    m.def("from_handle", from_handle<uint64_t, int64_t>);
    m.def("from_handle", from_handle<uint64_t, uint32_t>);
    m.def("from_handle", from_handle<uint64_t, uint64_t>);
    m.def("from_handle", from_handle<uint64_t, _Float64>);
    m.def("from_handle", from_handle<_Float64, int32_t>);
    m.def("from_handle", from_handle<_Float64, int64_t>);
    m.def("from_handle", from_handle<_Float64, uint32_t>);
    m.def("from_handle", from_handle<_Float64, uint64_t>);
    m.def("from_handle", from_handle<_Float64, _Float64>);
    m.def("ewise_ge", EwiseGe<int32_t, int32_t>);
    m.def("ewise_ge", EwiseGe<int32_t, int64_t>);
    m.def("ewise_ge", EwiseGe<int32_t, uint32_t>);
    m.def("ewise_ge", EwiseGe<int32_t, uint64_t>);
    m.def("ewise_ge", EwiseGe<int32_t, _Float64>);
    m.def("ewise_ge", EwiseGe<int64_t, int32_t>);
    m.def("ewise_ge", EwiseGe<int64_t, int64_t>);
    m.def("ewise_ge", EwiseGe<int64_t, uint32_t>);
    m.def("ewise_ge", EwiseGe<int64_t, uint64_t>);
    m.def("ewise_ge", EwiseGe<int64_t, _Float64>);
    m.def("ewise_ge", EwiseGe<uint32_t, int32_t>);
    m.def("ewise_ge", EwiseGe<uint32_t, int64_t>);
    m.def("ewise_ge", EwiseGe<uint32_t, uint32_t>);
    m.def("ewise_ge", EwiseGe<uint32_t, uint64_t>);
    m.def("ewise_ge", EwiseGe<uint32_t, _Float64>);
    m.def("ewise_ge", EwiseGe<uint64_t, int32_t>);
    m.def("ewise_ge", EwiseGe<uint64_t, int64_t>);
    m.def("ewise_ge", EwiseGe<uint64_t, uint32_t>);
    m.def("ewise_ge", EwiseGe<uint64_t, uint64_t>);
    m.def("ewise_ge", EwiseGe<uint64_t, _Float64>);
    m.def("ewise_ge", EwiseGe<_Float64, int32_t>);
    m.def("ewise_ge", EwiseGe<_Float64, int64_t>);
    m.def("ewise_ge", EwiseGe<_Float64, uint32_t>);
    m.def("ewise_ge", EwiseGe<_Float64, uint64_t>);
    m.def("ewise_ge", EwiseGe<_Float64, _Float64>);
    m.def("scalar_ge", ScalarGe<int32_t, int32_t>);
    m.def("scalar_ge", ScalarGe<int32_t, int64_t>);
    m.def("scalar_ge", ScalarGe<int32_t, uint32_t>);
    m.def("scalar_ge", ScalarGe<int32_t, uint64_t>);
    m.def("scalar_ge", ScalarGe<int32_t, _Float64>);
    m.def("scalar_ge", ScalarGe<int64_t, int32_t>);
    m.def("scalar_ge", ScalarGe<int64_t, int64_t>);
    m.def("scalar_ge", ScalarGe<int64_t, uint32_t>);
    m.def("scalar_ge", ScalarGe<int64_t, uint64_t>);
    m.def("scalar_ge", ScalarGe<int64_t, _Float64>);
    m.def("scalar_ge", ScalarGe<uint32_t, int32_t>);
    m.def("scalar_ge", ScalarGe<uint32_t, int64_t>);
    m.def("scalar_ge", ScalarGe<uint32_t, uint32_t>);
    m.def("scalar_ge", ScalarGe<uint32_t, uint64_t>);
    m.def("scalar_ge", ScalarGe<uint32_t, _Float64>);
    m.def("scalar_ge", ScalarGe<uint64_t, int32_t>);
    m.def("scalar_ge", ScalarGe<uint64_t, int64_t>);
    m.def("scalar_ge", ScalarGe<uint64_t, uint32_t>);
    m.def("scalar_ge", ScalarGe<uint64_t, uint64_t>);
    m.def("scalar_ge", ScalarGe<uint64_t, _Float64>);
    m.def("scalar_ge", ScalarGe<_Float64, int32_t>);
    m.def("scalar_ge", ScalarGe<_Float64, int64_t>);
    m.def("scalar_ge", ScalarGe<_Float64, uint32_t>);
    m.def("scalar_ge", ScalarGe<_Float64, uint64_t>);
    m.def("scalar_ge", ScalarGe<_Float64, _Float64>);
    m.def("ewise_add", EwiseAdd<int32_t, int32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, int32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, int32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, int32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, int32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<int32_t, int64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, int64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, int64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, int64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, int64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<int32_t, uint32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, uint32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, uint32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, uint32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, uint32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<int32_t, uint64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, uint64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, uint64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, uint64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, uint64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<int32_t, _Float64, int32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, _Float64, int64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, _Float64, uint32_t>);
    m.def("ewise_add", EwiseAdd<int32_t, _Float64, uint64_t>);
    m.def("ewise_add", EwiseAdd<int32_t, _Float64, _Float64>);
    m.def("ewise_add", EwiseAdd<int64_t, int32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, int32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, int32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, int32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, int32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<int64_t, int64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, int64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, int64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, int64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, int64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<int64_t, uint32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, uint32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, uint32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, uint32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, uint32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<int64_t, uint64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, uint64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, uint64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, uint64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, uint64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<int64_t, _Float64, int32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, _Float64, int64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, _Float64, uint32_t>);
    m.def("ewise_add", EwiseAdd<int64_t, _Float64, uint64_t>);
    m.def("ewise_add", EwiseAdd<int64_t, _Float64, _Float64>);
    m.def("ewise_add", EwiseAdd<uint32_t, int32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, int32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, int32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, int32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, int32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<uint32_t, int64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, int64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, int64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, int64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, int64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, uint64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<uint32_t, _Float64, int32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, _Float64, int64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, _Float64, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, _Float64, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint32_t, _Float64, _Float64>);
    m.def("ewise_add", EwiseAdd<uint64_t, int32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, int32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, int32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, int32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, int32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<uint64_t, int64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, int64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, int64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, int64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, int64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, uint64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<uint64_t, _Float64, int32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, _Float64, int64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, _Float64, uint32_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, _Float64, uint64_t>);
    m.def("ewise_add", EwiseAdd<uint64_t, _Float64, _Float64>);
    m.def("ewise_add", EwiseAdd<_Float64, int32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, int32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, int32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, int32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, int32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<_Float64, int64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, int64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, int64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, int64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, int64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<_Float64, uint32_t, int32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, uint32_t, int64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, uint32_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, uint32_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, uint32_t, _Float64>);
    m.def("ewise_add", EwiseAdd<_Float64, uint64_t, int32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, uint64_t, int64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, uint64_t, uint32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, uint64_t, uint64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, uint64_t, _Float64>);
    m.def("ewise_add", EwiseAdd<_Float64, _Float64, int32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, _Float64, int64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, _Float64, uint32_t>);
    m.def("ewise_add", EwiseAdd<_Float64, _Float64, uint64_t>);
    m.def("ewise_add", EwiseAdd<_Float64, _Float64, _Float64>);
    m.def("scalar_add", ScalarAdd<int32_t, int32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, int32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, int32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, int32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, int32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<int32_t, int64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, int64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, int64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, int64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, int64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<int32_t, uint32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, uint32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, uint32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, uint32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, uint32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<int32_t, uint64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, uint64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, uint64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, uint64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, uint64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<int32_t, _Float64, int32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, _Float64, int64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, _Float64, uint32_t>);
    m.def("scalar_add", ScalarAdd<int32_t, _Float64, uint64_t>);
    m.def("scalar_add", ScalarAdd<int32_t, _Float64, _Float64>);
    m.def("scalar_add", ScalarAdd<int64_t, int32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, int32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, int32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, int32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, int32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<int64_t, int64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, int64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, int64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, int64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, int64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<int64_t, uint32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, uint32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, uint32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, uint32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, uint32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<int64_t, uint64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, uint64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, uint64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, uint64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, uint64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<int64_t, _Float64, int32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, _Float64, int64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, _Float64, uint32_t>);
    m.def("scalar_add", ScalarAdd<int64_t, _Float64, uint64_t>);
    m.def("scalar_add", ScalarAdd<int64_t, _Float64, _Float64>);
    m.def("scalar_add", ScalarAdd<uint32_t, int32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, int32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, int32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, int32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, int32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<uint32_t, int64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, int64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, int64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, int64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, int64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, uint64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<uint32_t, _Float64, int32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, _Float64, int64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, _Float64, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, _Float64, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint32_t, _Float64, _Float64>);
    m.def("scalar_add", ScalarAdd<uint64_t, int32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, int32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, int32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, int32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, int32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<uint64_t, int64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, int64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, int64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, int64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, int64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, uint64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<uint64_t, _Float64, int32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, _Float64, int64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, _Float64, uint32_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, _Float64, uint64_t>);
    m.def("scalar_add", ScalarAdd<uint64_t, _Float64, _Float64>);
    m.def("scalar_add", ScalarAdd<_Float64, int32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, int32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, int32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, int32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, int32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<_Float64, int64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, int64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, int64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, int64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, int64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<_Float64, uint32_t, int32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, uint32_t, int64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, uint32_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, uint32_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, uint32_t, _Float64>);
    m.def("scalar_add", ScalarAdd<_Float64, uint64_t, int32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, uint64_t, int64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, uint64_t, uint32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, uint64_t, uint64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, uint64_t, _Float64>);
    m.def("scalar_add", ScalarAdd<_Float64, _Float64, int32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, _Float64, int64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, _Float64, uint32_t>);
    m.def("scalar_add", ScalarAdd<_Float64, _Float64, uint64_t>);
    m.def("scalar_add", ScalarAdd<_Float64, _Float64, _Float64>);
    m.def("ewise_mul", EwiseMul<int32_t, int32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, int32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, int32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, int32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, int32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<int32_t, int64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, int64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, int64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, int64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, int64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<int32_t, uint32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, uint32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, uint32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, uint32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, uint32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<int32_t, uint64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, uint64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, uint64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, uint64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, uint64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<int32_t, _Float64, int32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, _Float64, int64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, _Float64, uint32_t>);
    m.def("ewise_mul", EwiseMul<int32_t, _Float64, uint64_t>);
    m.def("ewise_mul", EwiseMul<int32_t, _Float64, _Float64>);
    m.def("ewise_mul", EwiseMul<int64_t, int32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, int32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, int32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, int32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, int32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<int64_t, int64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, int64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, int64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, int64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, int64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<int64_t, uint32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, uint32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, uint32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, uint32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, uint32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<int64_t, uint64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, uint64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, uint64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, uint64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, uint64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<int64_t, _Float64, int32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, _Float64, int64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, _Float64, uint32_t>);
    m.def("ewise_mul", EwiseMul<int64_t, _Float64, uint64_t>);
    m.def("ewise_mul", EwiseMul<int64_t, _Float64, _Float64>);
    m.def("ewise_mul", EwiseMul<uint32_t, int32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, int32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, int32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, int32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, int32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<uint32_t, int64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, int64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, int64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, int64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, int64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, uint64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<uint32_t, _Float64, int32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, _Float64, int64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, _Float64, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, _Float64, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint32_t, _Float64, _Float64>);
    m.def("ewise_mul", EwiseMul<uint64_t, int32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, int32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, int32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, int32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, int32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<uint64_t, int64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, int64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, int64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, int64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, int64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, uint64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<uint64_t, _Float64, int32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, _Float64, int64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, _Float64, uint32_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, _Float64, uint64_t>);
    m.def("ewise_mul", EwiseMul<uint64_t, _Float64, _Float64>);
    m.def("ewise_mul", EwiseMul<_Float64, int32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, int32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, int32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, int32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, int32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<_Float64, int64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, int64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, int64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, int64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, int64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<_Float64, uint32_t, int32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, uint32_t, int64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, uint32_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, uint32_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, uint32_t, _Float64>);
    m.def("ewise_mul", EwiseMul<_Float64, uint64_t, int32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, uint64_t, int64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, uint64_t, uint32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, uint64_t, uint64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, uint64_t, _Float64>);
    m.def("ewise_mul", EwiseMul<_Float64, _Float64, int32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, _Float64, int64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, _Float64, uint32_t>);
    m.def("ewise_mul", EwiseMul<_Float64, _Float64, uint64_t>);
    m.def("ewise_mul", EwiseMul<_Float64, _Float64, _Float64>);
    m.def("scalar_mul", ScalarMul<int32_t, int32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, int32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, int32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, int32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, int32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<int32_t, int64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, int64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, int64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, int64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, int64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<int32_t, uint32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, uint32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, uint32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, uint32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, uint32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<int32_t, uint64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, uint64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, uint64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, uint64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, uint64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<int32_t, _Float64, int32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, _Float64, int64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, _Float64, uint32_t>);
    m.def("scalar_mul", ScalarMul<int32_t, _Float64, uint64_t>);
    m.def("scalar_mul", ScalarMul<int32_t, _Float64, _Float64>);
    m.def("scalar_mul", ScalarMul<int64_t, int32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, int32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, int32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, int32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, int32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<int64_t, int64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, int64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, int64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, int64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, int64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<int64_t, uint32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, uint32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, uint32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, uint32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, uint32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<int64_t, uint64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, uint64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, uint64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, uint64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, uint64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<int64_t, _Float64, int32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, _Float64, int64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, _Float64, uint32_t>);
    m.def("scalar_mul", ScalarMul<int64_t, _Float64, uint64_t>);
    m.def("scalar_mul", ScalarMul<int64_t, _Float64, _Float64>);
    m.def("scalar_mul", ScalarMul<uint32_t, int32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, int32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, int32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, int32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, int32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<uint32_t, int64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, int64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, int64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, int64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, int64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, uint64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<uint32_t, _Float64, int32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, _Float64, int64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, _Float64, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, _Float64, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint32_t, _Float64, _Float64>);
    m.def("scalar_mul", ScalarMul<uint64_t, int32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, int32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, int32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, int32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, int32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<uint64_t, int64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, int64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, int64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, int64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, int64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, uint64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<uint64_t, _Float64, int32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, _Float64, int64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, _Float64, uint32_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, _Float64, uint64_t>);
    m.def("scalar_mul", ScalarMul<uint64_t, _Float64, _Float64>);
    m.def("scalar_mul", ScalarMul<_Float64, int32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, int32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, int32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, int32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, int32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<_Float64, int64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, int64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, int64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, int64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, int64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<_Float64, uint32_t, int32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, uint32_t, int64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, uint32_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, uint32_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, uint32_t, _Float64>);
    m.def("scalar_mul", ScalarMul<_Float64, uint64_t, int32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, uint64_t, int64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, uint64_t, uint32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, uint64_t, uint64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, uint64_t, _Float64>);
    m.def("scalar_mul", ScalarMul<_Float64, _Float64, int32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, _Float64, int64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, _Float64, uint32_t>);
    m.def("scalar_mul", ScalarMul<_Float64, _Float64, uint64_t>);
    m.def("scalar_mul", ScalarMul<_Float64, _Float64, _Float64>);
    m.def("ewise_div", EwiseDiv<int32_t, int32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, int32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, int32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, int32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, int32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<int32_t, int64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, int64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, int64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, int64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, int64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<int32_t, uint32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, uint32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, uint32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, uint32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, uint32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<int32_t, uint64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, uint64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, uint64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, uint64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, uint64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<int32_t, _Float64, int32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, _Float64, int64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, _Float64, uint32_t>);
    m.def("ewise_div", EwiseDiv<int32_t, _Float64, uint64_t>);
    m.def("ewise_div", EwiseDiv<int32_t, _Float64, _Float64>);
    m.def("ewise_div", EwiseDiv<int64_t, int32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, int32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, int32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, int32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, int32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<int64_t, int64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, int64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, int64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, int64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, int64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<int64_t, uint32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, uint32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, uint32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, uint32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, uint32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<int64_t, uint64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, uint64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, uint64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, uint64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, uint64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<int64_t, _Float64, int32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, _Float64, int64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, _Float64, uint32_t>);
    m.def("ewise_div", EwiseDiv<int64_t, _Float64, uint64_t>);
    m.def("ewise_div", EwiseDiv<int64_t, _Float64, _Float64>);
    m.def("ewise_div", EwiseDiv<uint32_t, int32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, int32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, int32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, int32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, int32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<uint32_t, int64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, int64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, int64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, int64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, int64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, uint64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<uint32_t, _Float64, int32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, _Float64, int64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, _Float64, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, _Float64, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint32_t, _Float64, _Float64>);
    m.def("ewise_div", EwiseDiv<uint64_t, int32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, int32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, int32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, int32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, int32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<uint64_t, int64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, int64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, int64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, int64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, int64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, uint64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<uint64_t, _Float64, int32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, _Float64, int64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, _Float64, uint32_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, _Float64, uint64_t>);
    m.def("ewise_div", EwiseDiv<uint64_t, _Float64, _Float64>);
    m.def("ewise_div", EwiseDiv<_Float64, int32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, int32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, int32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, int32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, int32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<_Float64, int64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, int64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, int64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, int64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, int64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<_Float64, uint32_t, int32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, uint32_t, int64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, uint32_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, uint32_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, uint32_t, _Float64>);
    m.def("ewise_div", EwiseDiv<_Float64, uint64_t, int32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, uint64_t, int64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, uint64_t, uint32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, uint64_t, uint64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, uint64_t, _Float64>);
    m.def("ewise_div", EwiseDiv<_Float64, _Float64, int32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, _Float64, int64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, _Float64, uint32_t>);
    m.def("ewise_div", EwiseDiv<_Float64, _Float64, uint64_t>);
    m.def("ewise_div", EwiseDiv<_Float64, _Float64, _Float64>);
    m.def("scalar_div", ScalarDiv<int32_t, int32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, int32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, int32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, int32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, int32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<int32_t, int64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, int64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, int64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, int64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, int64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<int32_t, uint32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, uint32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, uint32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, uint32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, uint32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<int32_t, uint64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, uint64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, uint64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, uint64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, uint64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<int32_t, _Float64, int32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, _Float64, int64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, _Float64, uint32_t>);
    m.def("scalar_div", ScalarDiv<int32_t, _Float64, uint64_t>);
    m.def("scalar_div", ScalarDiv<int32_t, _Float64, _Float64>);
    m.def("scalar_div", ScalarDiv<int64_t, int32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, int32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, int32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, int32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, int32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<int64_t, int64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, int64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, int64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, int64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, int64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<int64_t, uint32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, uint32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, uint32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, uint32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, uint32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<int64_t, uint64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, uint64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, uint64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, uint64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, uint64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<int64_t, _Float64, int32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, _Float64, int64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, _Float64, uint32_t>);
    m.def("scalar_div", ScalarDiv<int64_t, _Float64, uint64_t>);
    m.def("scalar_div", ScalarDiv<int64_t, _Float64, _Float64>);
    m.def("scalar_div", ScalarDiv<uint32_t, int32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, int32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, int32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, int32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, int32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<uint32_t, int64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, int64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, int64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, int64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, int64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, uint64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<uint32_t, _Float64, int32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, _Float64, int64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, _Float64, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, _Float64, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint32_t, _Float64, _Float64>);
    m.def("scalar_div", ScalarDiv<uint64_t, int32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, int32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, int32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, int32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, int32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<uint64_t, int64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, int64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, int64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, int64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, int64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, uint64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<uint64_t, _Float64, int32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, _Float64, int64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, _Float64, uint32_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, _Float64, uint64_t>);
    m.def("scalar_div", ScalarDiv<uint64_t, _Float64, _Float64>);
    m.def("scalar_div", ScalarDiv<_Float64, int32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, int32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, int32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, int32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, int32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<_Float64, int64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, int64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, int64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, int64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, int64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<_Float64, uint32_t, int32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, uint32_t, int64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, uint32_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, uint32_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, uint32_t, _Float64>);
    m.def("scalar_div", ScalarDiv<_Float64, uint64_t, int32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, uint64_t, int64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, uint64_t, uint32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, uint64_t, uint64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, uint64_t, _Float64>);
    m.def("scalar_div", ScalarDiv<_Float64, _Float64, int32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, _Float64, int64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, _Float64, uint32_t>);
    m.def("scalar_div", ScalarDiv<_Float64, _Float64, uint64_t>);
    m.def("scalar_div", ScalarDiv<_Float64, _Float64, _Float64>);
    m.def("matmul", Matmul<int32_t, int32_t, int32_t>);
    m.def("matmul", Matmul<int32_t, int32_t, int64_t>);
    m.def("matmul", Matmul<int32_t, int32_t, uint32_t>);
    m.def("matmul", Matmul<int32_t, int32_t, uint64_t>);
    m.def("matmul", Matmul<int32_t, int32_t, _Float64>);
    m.def("matmul", Matmul<int32_t, int64_t, int32_t>);
    m.def("matmul", Matmul<int32_t, int64_t, int64_t>);
    m.def("matmul", Matmul<int32_t, int64_t, uint32_t>);
    m.def("matmul", Matmul<int32_t, int64_t, uint64_t>);
    m.def("matmul", Matmul<int32_t, int64_t, _Float64>);
    m.def("matmul", Matmul<int32_t, uint32_t, int32_t>);
    m.def("matmul", Matmul<int32_t, uint32_t, int64_t>);
    m.def("matmul", Matmul<int32_t, uint32_t, uint32_t>);
    m.def("matmul", Matmul<int32_t, uint32_t, uint64_t>);
    m.def("matmul", Matmul<int32_t, uint32_t, _Float64>);
    m.def("matmul", Matmul<int32_t, uint64_t, int32_t>);
    m.def("matmul", Matmul<int32_t, uint64_t, int64_t>);
    m.def("matmul", Matmul<int32_t, uint64_t, uint32_t>);
    m.def("matmul", Matmul<int32_t, uint64_t, uint64_t>);
    m.def("matmul", Matmul<int32_t, uint64_t, _Float64>);
    m.def("matmul", Matmul<int32_t, _Float64, int32_t>);
    m.def("matmul", Matmul<int32_t, _Float64, int64_t>);
    m.def("matmul", Matmul<int32_t, _Float64, uint32_t>);
    m.def("matmul", Matmul<int32_t, _Float64, uint64_t>);
    m.def("matmul", Matmul<int32_t, _Float64, _Float64>);
    m.def("matmul", Matmul<int64_t, int32_t, int32_t>);
    m.def("matmul", Matmul<int64_t, int32_t, int64_t>);
    m.def("matmul", Matmul<int64_t, int32_t, uint32_t>);
    m.def("matmul", Matmul<int64_t, int32_t, uint64_t>);
    m.def("matmul", Matmul<int64_t, int32_t, _Float64>);
    m.def("matmul", Matmul<int64_t, int64_t, int32_t>);
    m.def("matmul", Matmul<int64_t, int64_t, int64_t>);
    m.def("matmul", Matmul<int64_t, int64_t, uint32_t>);
    m.def("matmul", Matmul<int64_t, int64_t, uint64_t>);
    m.def("matmul", Matmul<int64_t, int64_t, _Float64>);
    m.def("matmul", Matmul<int64_t, uint32_t, int32_t>);
    m.def("matmul", Matmul<int64_t, uint32_t, int64_t>);
    m.def("matmul", Matmul<int64_t, uint32_t, uint32_t>);
    m.def("matmul", Matmul<int64_t, uint32_t, uint64_t>);
    m.def("matmul", Matmul<int64_t, uint32_t, _Float64>);
    m.def("matmul", Matmul<int64_t, uint64_t, int32_t>);
    m.def("matmul", Matmul<int64_t, uint64_t, int64_t>);
    m.def("matmul", Matmul<int64_t, uint64_t, uint32_t>);
    m.def("matmul", Matmul<int64_t, uint64_t, uint64_t>);
    m.def("matmul", Matmul<int64_t, uint64_t, _Float64>);
    m.def("matmul", Matmul<int64_t, _Float64, int32_t>);
    m.def("matmul", Matmul<int64_t, _Float64, int64_t>);
    m.def("matmul", Matmul<int64_t, _Float64, uint32_t>);
    m.def("matmul", Matmul<int64_t, _Float64, uint64_t>);
    m.def("matmul", Matmul<int64_t, _Float64, _Float64>);
    m.def("matmul", Matmul<uint32_t, int32_t, int32_t>);
    m.def("matmul", Matmul<uint32_t, int32_t, int64_t>);
    m.def("matmul", Matmul<uint32_t, int32_t, uint32_t>);
    m.def("matmul", Matmul<uint32_t, int32_t, uint64_t>);
    m.def("matmul", Matmul<uint32_t, int32_t, _Float64>);
    m.def("matmul", Matmul<uint32_t, int64_t, int32_t>);
    m.def("matmul", Matmul<uint32_t, int64_t, int64_t>);
    m.def("matmul", Matmul<uint32_t, int64_t, uint32_t>);
    m.def("matmul", Matmul<uint32_t, int64_t, uint64_t>);
    m.def("matmul", Matmul<uint32_t, int64_t, _Float64>);
    m.def("matmul", Matmul<uint32_t, uint32_t, int32_t>);
    m.def("matmul", Matmul<uint32_t, uint32_t, int64_t>);
    m.def("matmul", Matmul<uint32_t, uint32_t, uint32_t>);
    m.def("matmul", Matmul<uint32_t, uint32_t, uint64_t>);
    m.def("matmul", Matmul<uint32_t, uint32_t, _Float64>);
    m.def("matmul", Matmul<uint32_t, uint64_t, int32_t>);
    m.def("matmul", Matmul<uint32_t, uint64_t, int64_t>);
    m.def("matmul", Matmul<uint32_t, uint64_t, uint32_t>);
    m.def("matmul", Matmul<uint32_t, uint64_t, uint64_t>);
    m.def("matmul", Matmul<uint32_t, uint64_t, _Float64>);
    m.def("matmul", Matmul<uint32_t, _Float64, int32_t>);
    m.def("matmul", Matmul<uint32_t, _Float64, int64_t>);
    m.def("matmul", Matmul<uint32_t, _Float64, uint32_t>);
    m.def("matmul", Matmul<uint32_t, _Float64, uint64_t>);
    m.def("matmul", Matmul<uint32_t, _Float64, _Float64>);
    m.def("matmul", Matmul<uint64_t, int32_t, int32_t>);
    m.def("matmul", Matmul<uint64_t, int32_t, int64_t>);
    m.def("matmul", Matmul<uint64_t, int32_t, uint32_t>);
    m.def("matmul", Matmul<uint64_t, int32_t, uint64_t>);
    m.def("matmul", Matmul<uint64_t, int32_t, _Float64>);
    m.def("matmul", Matmul<uint64_t, int64_t, int32_t>);
    m.def("matmul", Matmul<uint64_t, int64_t, int64_t>);
    m.def("matmul", Matmul<uint64_t, int64_t, uint32_t>);
    m.def("matmul", Matmul<uint64_t, int64_t, uint64_t>);
    m.def("matmul", Matmul<uint64_t, int64_t, _Float64>);
    m.def("matmul", Matmul<uint64_t, uint32_t, int32_t>);
    m.def("matmul", Matmul<uint64_t, uint32_t, int64_t>);
    m.def("matmul", Matmul<uint64_t, uint32_t, uint32_t>);
    m.def("matmul", Matmul<uint64_t, uint32_t, uint64_t>);
    m.def("matmul", Matmul<uint64_t, uint32_t, _Float64>);
    m.def("matmul", Matmul<uint64_t, uint64_t, int32_t>);
    m.def("matmul", Matmul<uint64_t, uint64_t, int64_t>);
    m.def("matmul", Matmul<uint64_t, uint64_t, uint32_t>);
    m.def("matmul", Matmul<uint64_t, uint64_t, uint64_t>);
    m.def("matmul", Matmul<uint64_t, uint64_t, _Float64>);
    m.def("matmul", Matmul<uint64_t, _Float64, int32_t>);
    m.def("matmul", Matmul<uint64_t, _Float64, int64_t>);
    m.def("matmul", Matmul<uint64_t, _Float64, uint32_t>);
    m.def("matmul", Matmul<uint64_t, _Float64, uint64_t>);
    m.def("matmul", Matmul<uint64_t, _Float64, _Float64>);
    m.def("matmul", Matmul<_Float64, int32_t, int32_t>);
    m.def("matmul", Matmul<_Float64, int32_t, int64_t>);
    m.def("matmul", Matmul<_Float64, int32_t, uint32_t>);
    m.def("matmul", Matmul<_Float64, int32_t, uint64_t>);
    m.def("matmul", Matmul<_Float64, int32_t, _Float64>);
    m.def("matmul", Matmul<_Float64, int64_t, int32_t>);
    m.def("matmul", Matmul<_Float64, int64_t, int64_t>);
    m.def("matmul", Matmul<_Float64, int64_t, uint32_t>);
    m.def("matmul", Matmul<_Float64, int64_t, uint64_t>);
    m.def("matmul", Matmul<_Float64, int64_t, _Float64>);
    m.def("matmul", Matmul<_Float64, uint32_t, int32_t>);
    m.def("matmul", Matmul<_Float64, uint32_t, int64_t>);
    m.def("matmul", Matmul<_Float64, uint32_t, uint32_t>);
    m.def("matmul", Matmul<_Float64, uint32_t, uint64_t>);
    m.def("matmul", Matmul<_Float64, uint32_t, _Float64>);
    m.def("matmul", Matmul<_Float64, uint64_t, int32_t>);
    m.def("matmul", Matmul<_Float64, uint64_t, int64_t>);
    m.def("matmul", Matmul<_Float64, uint64_t, uint32_t>);
    m.def("matmul", Matmul<_Float64, uint64_t, uint64_t>);
    m.def("matmul", Matmul<_Float64, uint64_t, _Float64>);
    m.def("matmul", Matmul<_Float64, _Float64, int32_t>);
    m.def("matmul", Matmul<_Float64, _Float64, int64_t>);
    m.def("matmul", Matmul<_Float64, _Float64, uint32_t>);
    m.def("matmul", Matmul<_Float64, _Float64, uint64_t>);
    m.def("matmul", Matmul<_Float64, _Float64, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, int64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, uint64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int32_t, _Float64, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, _Float64, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, _Float64, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, _Float64, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int32_t, _Float64, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, int64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, uint64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<int64_t, _Float64, int32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, _Float64, int64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, _Float64, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, _Float64, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<int64_t, _Float64, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, int64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, uint64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, _Float64, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, _Float64, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, _Float64, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, _Float64, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint32_t, _Float64, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, int64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, uint64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, _Float64, int32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, _Float64, int64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, _Float64, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, _Float64, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<uint64_t, _Float64, _Float64>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, int64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint32_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint32_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint32_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint32_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint32_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint64_t, int32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint64_t, int64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint64_t, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint64_t, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, uint64_t, _Float64>);
    m.def("matmul_tiled", MatmulTiled<_Float64, _Float64, int32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, _Float64, int64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, _Float64, uint32_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, _Float64, uint64_t>);
    m.def("matmul_tiled", MatmulTiled<_Float64, _Float64, _Float64>);
